alias la="ls -al"
alias rc="source $HOME/.config/fish/config.fish"
alias fulldate="date +%A,\ %d\ %b,\ %l:%M\ %p"
alias g="git"
alias n="notes"
alias ns="notes -s"
alias p="pwd | pbcopy"
alias dot="cd ~/.dotfiles"
alias u="url"
alias c="cd ~/Code"
alias al="add_alias"
alias dt="cd ~/.dotfiles"
alias t="tmux"
alias tk=kill-session -t=""
alias tk=tmux kill-session -t=""
